#pragma once
/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include


#include <wx/filedlg.h>
#include <wx/msw/filedlg.h>
#include <wx/dcbuffer.h>
#include <wx/window.h>

#include "CImg.h"
#include <FreeImage.h>

/** Implementing MyFrame1 */
class GUIMyFrame : public MyFrame
{
	protected:
		// Handlers for MyFrame1 events.
		void onUpdateUI(wxUpdateUIEvent& event) override;
		void loadImageHandler( wxCommandEvent& event ) override;
		void putCenzureHandler( wxCommandEvent& event ) override;
		void erodeHandler( wxCommandEvent& event ) override;
		void animationHandler( wxCommandEvent& event ) override;
		
		wxImage* m_image;
		wxImage* m_original_image;

	public:
		GUIMyFrame( wxWindow* parent );
		void refresh(wxClientDC& dc) const;
		~GUIMyFrame();
};
